# Generated by Django 3.2.4 on 2021-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatar',
            name='power',
            field=models.CharField(max_length=359),
        ),
    ]
