# Generated by Django 3.2.6 on 2021-08-22 21:27

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=299, unique=True)),
                ('password', models.CharField(help_text='Must have up to 8 - 20 characters', max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True, default='')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=249)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.friend')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.player'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=369, unique=True)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='leader', serialize=False, to='users.player')),
                ('logo', models.ImageField(unique=True, upload_to='')),
                ('doc', models.TextField(unique=True, verbose_name='Documentation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('capturer', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capturer', to='users.player')),
                ('defender', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defender', to='users.player')),
                ('middlemen', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='middlemen', to='users.player')),
            ],
        ),
    ]
