# Generated by Django 3.2.4 on 2021-07-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=299, unique=True)),
                ('password', models.CharField(help_text='Must have up to 8 characters', max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('location', models.CharField(help_text='Make sure it is a valid country or city', max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=369, unique=True)),
                ('leader', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='users.player')),
                ('logo', models.ImageField(unique=True, upload_to='')),
                ('doc', models.TextField(unique=True, verbose_name='Documentation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('capturer', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player')),
                ('defender', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player')),
                ('middlemen', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player')),
            ],
        ),
    ]
