# Generated by Django 3.2.4 on 2021-06-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_auto_20210628_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=369, unique=True)),
                ('group_leader', models.CharField(max_length=299, unique=True)),
                ('logo', models.ImageField(unique=True, upload_to='')),
                ('doc', models.TextField(unique=True, verbose_name='Documentation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=299, unique=True)),
                ('password', models.CharField(help_text='Must have up to 8 characters', max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('location', models.CharField(help_text='Make sure it is a valid country or city', max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='You can either be a defence, midfielder, capturer', max_length=249)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default=[''], to='users.Player'),
        ),
    ]
