# Generated by Django 3.2.4 on 2021-06-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(default='email@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
