# Generated by Django 3.2.4 on 2021-07-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_group_group_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
