# Generated by Django 3.2.4 on 2021-06-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210628_2011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Must have upto 8 characters', max_length=20)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.avatar')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
