# Generated by Django 3.2.4 on 2021-07-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='capturer',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player'),
        ),
    ]
