# Generated by Django 3.2.4 on 2021-07-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210702_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=369, unique=True)),
                ('logo', models.ImageField(unique=True, upload_to='')),
                ('doc', models.TextField(unique=True, verbose_name='Documentation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, default=[''], to='users.Player')),
            ],
        ),
    ]
