# Generated by Django 3.2.4 on 2021-07-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_group_capturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='defender',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player'),
        ),
        migrations.AlterField(
            model_name='group',
            name='middlemen',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player'),
        ),
    ]
