# Generated by Django 3.2.4 on 2021-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile',
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.CharField(default='', help_text='Make sure it is a valid country or city', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(help_text='Must have up to 8 characters', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=299),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
