# Generated by Django 3.2.4 on 2021-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_leader',
            field=models.CharField(default='', max_length=356, unique=True),
            preserve_default=False,
        ),
    ]
