# Generated by Django 3.2.4 on 2021-07-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210708_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
