# Generated by Django 3.2.4 on 2021-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210630_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(help_text='Must have up to 8 characters', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=299, unique=True),
        ),
    ]
