# Generated by Django 3.2.4 on 2021-07-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_group_group_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_leader',
        ),
    ]
