# Generated by Django 3.2.4 on 2021-07-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.player'),
        ),
    ]
