# Generated by Django 3.2.3 on 2021-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210823_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
