# Generated by Django 3.2.4 on 2021-07-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_group_group_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='You can either be a defence, midfielder, capturer', max_length=249)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
    ]
