# Generated by Django 3.2.3 on 2021-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_player_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
