# Generated by Django 3.2.4 on 2021-07-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210709_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
    ]
