# Generated by Django 3.2.3 on 2021-08-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_group_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='To',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
