# Generated by Django 3.2.4 on 2021-07-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
