# Generated by Django 3.2.3 on 2021-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210824_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='doc',
            field=models.TextField(verbose_name='Documentation'),
        ),
    ]
