# Generated by Django 3.2.4 on 2021-07-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_friend_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
