# Generated by Django 3.2.3 on 2021-08-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_group_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to=''),
        ),
    ]
