# Generated by Django 3.2.6 on 2021-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210709_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(help_text='Must have up to 8 - 20 characters', max_length=20, unique=True),
        ),
    ]
