# Generated by Django 3.2.3 on 2021-08-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='just_joined',
            field=models.BooleanField(default=False),
        ),
    ]
