# Generated by Django 3.2.6 on 2021-08-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
