# Generated by Django 3.2.6 on 2021-08-09 14:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_player_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
