# Generated by Django 3.2.6 on 2021-08-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_player_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='capturer',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.player'),
        ),
        migrations.AlterField(
            model_name='group',
            name='defender',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.player'),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='users.player'),
        ),
        migrations.AlterField(
            model_name='group',
            name='middlemen',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.player'),
        ),
    ]
